### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by kiote** [RailsApps/rails3-bootstrap-devise-cancan#1]
I've tried your template under MacOS Lion, rvm, ruby 1.9.3 and got:

apply  https://raw.github.com/RailsApps/rails3-application-templates/master/rails3-bootstrap-devise-cancan-template.rb
/Users/kiote/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
    from /Users/kiote/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:799:in`block in connect'

Not sure it's app issuse or my system problem, may be you know better?

**Comment by DanielKehoe** [comment]
This may help:
http://railsapps.github.com/openssl-certificate-verify-failed.html

Please reply here if you resolve your problem. If the suggestions don't help, leave details in the comments on the article/guide page.
