### ISSUE TITLE
alerts issues with devise and bootstrap

### ISSUE THREAD

**Issue by richardjortega** [RailsApps/rails3-bootstrap-devise-cancan#11]
I followed your tutorials (which are awesome), but there's one inconsistency that's really getting me and should be updated. Your Flash message don't use the Twitter Bootstrap. Even though you reference it. When you setup "devise_error_messages!", the default for error messages with Devise forms its return doesn't use Bootstrap styling. 

I'd love to know how to fix this as my app is looking kinda fugly without it. Thanks.

**Comment by DanielKehoe** [comment]
Sorry to say it took so long to get to this issue, but it is resolved now. I've reworked the Devise forms so error messages use the proper Bootstrap styling for the rails3-bootstrap-devise-cancan example application.
