### ISSUE TITLE
getaddrinfo: No such host is known.  (SocketError)

### ISSUE THREAD

**Issue by udokrass** [RailsApps/rails3-bootstrap-devise-cancan#12]
Hi all,

When I run the command "rails new myapp -m https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-bootstrap-devise-cancan-template.rb -T"

I get following error:
"apply  https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-bootstrap-devise-cancan-template.rb
/lib/ruby/1.9.1/net/http.rb:762:in `initialize': getaddrinfo: No such host is known.  (SocketError)"

How can I fix this?

Regards,
Udo

**Comment by DanielKehoe** [comment]
I suggest to review the article 
http://railsapps.github.com/installing-rails.html
and also look at
http://railsapps.github.com/openssl-certificate-verify-failed.html

**Comment by DanielKehoe** [comment]
Closed issue due to lack of response.
