### ISSUE TITLE
Segmentation fault ruby 1.8.7

### ISSUE THREAD

**Issue by buk** [RailsApps/rails3-bootstrap-devise-cancan#15]
Hi,

i have cloned your tutorial _git clone git://github.com/RailsApps/rails3-bootstrap-devise-cancan.git myApp_ 
After this i changed into this directory running _rake db:migrate_ and _rake:db seed_ 
After running _rails s_ this error appears: 

> /Users/sebastian/.rvm/gems/ruby-1.9.3-p194@rails3-bootstrap-devise-cancan/gems/sqlite3- >1.3.6/lib/sqlite3/sqlite3_native.bundle: [BUG] Segmentation fault
> ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

I am running *ruby 1.9.3p194

What am i doing wrong?

Thx and regards,
buk

**Comment by DanielKehoe** [comment]
Looks like problems with rvm. I recommend going through this article step by step:
http://railsapps.github.com/installing-rails.html
