### ISSUE TITLE
Tutorial says to add confirmed_at as an attr_accessible

### ISSUE THREAD

**Issue by patrickdavey** [RailsApps/rails3-bootstrap-devise-cancan#16]
Hi there,

Firstly - nice work!  Am enjoying looking through some of the tutorials.

Just a quick question.. on:
http://railsapps.github.com/tutorials-rails-bootstrap-devise-cancan.html

You say "If you’ve chosen to create the application with the Devise Confirmable module, also add :confirmed_at:" to the attr_accessible.

I've run the rails_composer for this repo - added confirmable to my devise user model, generated the necessary migrations and tested (just in the browser at this stage) that I can confirm without having confirmed_at as an attr_accessible.

Just wondering if this is a documentation error (in which case I'm more than happy to submit a pull request) or if there's something obvious I'm missing.

All the best,
Patrick

**Comment by schadenfred** [comment]
Should confirmed_at be mass assignable?

**Comment by patrickdavey** [comment]
Heh, "Should confirmed_at be mass assignable?"  - that's a much nicer way of saying it!

I can't see why it would be mass assignable (I certainly don't have it as such in a side project - devise 1.5.3)

**Comment by schadenfred** [comment]
:)

I'm always confused by how Devise works.  It's kind of magical.  Is
confirmed_at a parameter that comes in from a request, or simply a
timestamp that is added on create by Rails?  If the former it needs to be
mass assignable, if the latter it shouldn't need to be.  I'll figure it out
and put in a pull request for Daniel if I can figure it out.

**Comment by patrickdavey** [comment]
Am going to close this issue, as it's really about the documentation rather than the code itself.

Have opened https://github.com/DanielKehoe/tutorials-railsapps/issues/1 and have sent a pull request https://github.com/DanielKehoe/tutorials-railsapps/pull/2

Closing
