### ISSUE TITLE
How make some actions to be accessable only for VIP ?

### ISSUE THREAD

**Issue by mitchpolska** [RailsApps/rails3-bootstrap-devise-cancan#17]
Hi,
How can I use VIP role ?
Like this: before_filter :authenticate_VIP!, :only => :new

Thank you in advance

**Comment by DanielKehoe** [comment]
Have you looked at the tutorial? See the sections "Set Up Authorization" and "Set Up a Demonstration of CanCan". Let me know if the explanation is not sufficient.
