### ISSUE TITLE
'Change Role' Modal does nothing on Admin page

### ISSUE THREAD

**Issue by gregelizondo** [RailsApps/rails3-bootstrap-devise-cancan#18]
I have compared my hand coded version of the app with a clone from GitHub. I wasn't able to notice any significant differences.

When I am on the /users page, the 'Change Role' button does nothing. The address bar changes to, "http://localhost:3000/users#role-options-2" but I don't see any sort of overlay.

Any ideas?

**Comment by DanielKehoe** [comment]
The repo version works as expected. You could try generating the application using the Rails Composer tool and see what you get.

**Comment by gregelizondo** [comment]
Hm, the repo version does work fine.

Not sure where I went wrong on my end, though. I tried just copy/pasting from the "Improve the Administrative Dashboard" heading in the tutorial but still no luck. I originally transcribed everything by hand so I must have just missed something.

Oh well, thanks for your help, Daniel. I'll keep looking into on my own. By the way, thanks for all the tutorials. Keep up the great work.

**Comment by DanielKehoe** [comment]
Did you use a file compare tool to look for differences? On a Mac, good file compare tools are FileMerge, DiffMerge, Kaleidoscope, or Ian Baird’s Changes. Sometimes it is difficult to eyeball differences without using a tool.

I'm glad the tutorials are helpful. Let me know if you need further help.

**Comment by gregelizondo** [comment]
Yea, I gave DiffMerge a shot and couldn't find anything besides the random space here and there. Obviously I must have missed something, though. Maybe I'll give it another look with fresh eyes and see if anything jumps out at me.

**Comment by SimonBirrell** [comment]
Did you find the cause? Same thing's happening to me...

**Comment by gregelizondo** [comment]
Never did figure it out. Best of luck.
