### ISSUE TITLE
Error: You have already activated rake 0.9.2.2, but your Gemfile requires rake 10.0.2.

### ISSUE THREAD

**Issue by kevinelliott** [RailsApps/rails3-bootstrap-devise-cancan#19]
1.9.3 Kevins-MacBook-Pro:~/work/partners $ rails -v
Rails 3.2.9
1.9.3 Kevins-MacBook-Pro:~/work/partners $ rails new RQueuePrototype  -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb -T
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/images/rails.png
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/mailers
      create  app/models
      create  app/views/layouts/application.html.erb
      create  app/mailers/.gitkeep
      create  app/models/.gitkeep
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/secret_token.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  doc
      create  doc/README_FOR_APP
      create  lib
      create  lib/tasks
      create  lib/tasks/.gitkeep
      create  lib/assets
      create  lib/assets/.gitkeep
      create  log
      create  log/.gitkeep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/index.html
      create  public/robots.txt
      create  script
      create  script/rails
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.gitkeep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.gitkeep
      create  vendor/plugins
      create  vendor/plugins/.gitkeep
       apply  https://raw.github.com/RailsApps/rails-composer/master/composer.rb
         run    bundle update from "."
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Installing rake (10.0.2) 
Using i18n (0.6.1) 
Installing multi_json (1.3.7) 
Using activesupport (3.2.9) 
Installing builder (3.0.4) 
Using activemodel (3.2.9) 
Using erubis (2.7.0) 
Using journey (1.0.4) 
Using rack (1.4.1) 
Using rack-cache (1.2) 
Using rack-test (0.6.2) 
Using hike (1.2.1) 
Using tilt (1.3.3) 
Using sprockets (2.2.1) 
Using actionpack (3.2.9) 
Using mime-types (1.19) 
Using polyglot (0.3.3) 
Installing treetop (1.4.12) 
Using mail (2.4.4) 
Using actionmailer (3.2.9) 
Using arel (3.0.2) 
Installing tzinfo (0.3.35) 
Using activerecord (3.2.9) 
Using activeresource (3.2.9) 
Using bundler (1.1.4) 
Installing coffee-script-source (1.4.0) 
Using execjs (1.4.0) 
Using coffee-script (2.2.0) 
Using rack-ssl (1.3.2) 
Using json (1.7.5) 
Using rdoc (3.12) 
Using thor (0.16.0) 
Using railties (3.2.9) 
Using coffee-rails (3.2.2) 
Using jquery-rails (2.1.3) 
Using rails (3.2.9) 
Installing sass (3.2.3) 
Using sass-rails (3.2.5) 
Using sqlite3 (1.3.6) 
Using uglifier (1.3.0) 
Your bundle is updated! Use `bundle show [gemname]` to see where a bundled gem is installed.
 initializer    generators.rb
    composer  WOOT! The recipes you've selected are known to work together.
    composer  Using rails_apps_composer recipes to generate an application.
      insert    config/application.rb
      recipe  Running core recipe...
        core  selected all core recipes
      recipe  Running git recipe...
         git  initialize git
      remove    .gitignore
      create    .gitignore
         run    git init from "."
Initialized empty Git repository in /Volumes/San Francisco/Users Extras/kevin/Dropbox/work/partners/RQueuePrototype/.git/
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: initial commit" from "."
      recipe  Running railsapps recipe...
    question  Install an example application?
          1)  I want to build my own application
          2)  rails-stripe-membership-saas
          3)  rails-prelaunch-signup
          4)  rails3-bootstrap-devise-cancan
          5)  rails3-devise-rspec-cucumber
          6)  rails3-mongoid-devise
          7)  rails3-mongoid-omniauth
          8)  rails3-subdomains
   railsapps  Enter your selection: 4
      recipe  Running setup recipe...
       setup  Your operating system is darwin12.0.0.
       setup  You are using Ruby version 1.9.3.
       setup  You are using Rails version 3.2.9.
    question  Web server for development?
          1)  WEBrick (default)
          2)  Thin
          3)  Unicorn
          4)  Puma
       setup  Enter your selection: 2
    question  Web server for production?
          1)  Same as development
          2)  Thin
          3)  Unicorn
          4)  Puma
       setup  Enter your selection: 2
    question  Template engine?
          1)  ERB
          2)  Haml
          3)  Slim (experimental)
       setup  Enter your selection: 2
      create    README
      append    README
      recipe  Running readme recipe...
      recipe  Running gems recipe...
     gemfile    thin (>= 1.5.0)
     gemfile    haml (>= 3.1.7)
     gemfile    haml-rails (>= 0.3.5)
     gemfile    hpricot (>= 0.8.6)
     gemfile    ruby_parser (>= 3.0.1)
     gemfile    rspec-rails (>= 2.11.4)
     gemfile    database_cleaner (>= 0.9.1)
     gemfile    email_spec (>= 1.4.0)
     gemfile    cucumber-rails (>= 1.3.0)
     gemfile    launchy (>= 2.1.2)
     gemfile    capybara (>= 1.1.3)
     gemfile    factory_girl_rails (>= 4.1.0)
     gemfile    bootstrap-sass (>= 2.1.1.0)
     gemfile    devise (>= 2.1.2)
     gemfile    cancan (>= 1.6.8)
     gemfile    rolify (>= 3.2.0)
     gemfile    simple_form (>= 2.0.4)
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: Gemfile" from "."
      recipe  Running testing recipe...
      recipe  Running email recipe...
      recipe  Running models recipe...
      recipe  Running controllers recipe...
      recipe  Running views recipe...
      recipe  Running routes recipe...
      recipe  Running frontend recipe...
      recipe  Running init recipe...
      recipe  Running prelaunch recipe...
      recipe  Running prelaunch recipe...
      recipe  Running extras recipe...
      extras  Set a robots.txt file to ban spiders? (y/n) n
      extras  Create a project-specific rvm gemset and .rvmrc? (y/n) y
      extras  Create a GitHub repository? (y/n) y
      extras  recipe setting quiet_assets for reduced asset pipeline logging
     gemfile    quiet_assets (>= 1.0.1)
      extras  recipe creating project-specific rvm gemset and .rvmrc
      extras  creating RVM gemset 'RQueuePrototype'
         run    rvm rvmrc trust from "."
Marked /Volumes/San Francisco/Users Extras/kevin/Dropbox/work/partners/RQueuePrototype/Gemfile as trusted
      extras  switching to gemset 'RQueuePrototype'
         run    rvm gemset list from "."

gemsets for ruby-1.9.3-p194 (found in /Users/kevin/.rvm/gems/ruby-1.9.3-p194)
=> RQueuePrototype
   admin
   blue_kai_test
   edgerails-test1
   global
   learn_tribe
   rate_card

```
  remove    .rvmrc
  create    .rvmrc
    gsub    .rvmrc
 gemfile    hub (>= 1.10.2)
composer  Installing gems. This will take a while.
     run    bundle install --without production from "."
```

Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Installing rake (10.0.2) 
Installing i18n (0.6.1) 
Installing multi_json (1.3.7) 
Installing activesupport (3.2.9) 
Installing builder (3.0.4) 
Installing activemodel (3.2.9) 
Installing erubis (2.7.0) 
Installing journey (1.0.4) 
Installing rack (1.4.1) 
Installing rack-cache (1.2) 
Installing rack-test (0.6.2) 
Installing hike (1.2.1) 
Installing tilt (1.3.3) 
Installing sprockets (2.2.1) 
Installing actionpack (3.2.9) 
Installing mime-types (1.19) 
Installing polyglot (0.3.3) 
Installing treetop (1.4.12) 
Installing mail (2.4.4) 
Installing actionmailer (3.2.9) 
Installing arel (3.0.2) 
Installing tzinfo (0.3.35) 
Installing activerecord (3.2.9) 
Installing activeresource (3.2.9) 
Installing addressable (2.3.2) 
Installing bcrypt-ruby (3.0.1) with native extensions 
Installing sass (3.2.3) 
Installing bootstrap-sass (2.2.1.1) 
Using bundler (1.1.4) 
Installing cancan (1.6.8) 
Installing nokogiri (1.5.5) with native extensions 
Installing ffi (1.2.0) with native extensions 
Installing childprocess (0.3.6) 
Installing websocket (1.0.3) 
Installing libwebsocket (0.1.6.1) 
Installing rubyzip (0.9.9) 
Installing selenium-webdriver (2.26.0) 
Installing xpath (1.0.0) 
Installing capybara (2.0.0) 
Installing coffee-script-source (1.4.0) 
Installing execjs (1.4.0) 
Installing coffee-script (2.2.0) 
Installing rack-ssl (1.3.2) 
Installing json (1.7.5) with native extensions 
Installing rdoc (3.12) 
Installing thor (0.16.0) 
Installing railties (3.2.9) 
Installing coffee-rails (3.2.2) 
Installing diff-lcs (1.1.3) 
Installing gherkin (2.11.5) with native extensions 
Installing cucumber (1.2.1) 
Installing cucumber-rails (1.3.0) 
Installing daemons (1.1.9) 
Installing database_cleaner (0.9.1) 
Installing orm_adapter (0.4.0) 
Installing warden (1.2.1) 
Installing devise (2.1.2) 
Installing launchy (2.1.2) 
Installing email_spec (1.4.0) 
Installing eventmachine (1.0.0) with native extensions 
Installing factory_girl (4.1.0) 
Installing factory_girl_rails (4.1.0) 
Installing haml (3.1.7) 
Installing haml-rails (0.3.5) 
Installing hpricot (0.8.6) with native extensions 
Installing hub (1.10.2) 
Installing jquery-rails (2.1.3) 
Installing quiet_assets (1.0.1) 
Installing rails (3.2.9) 
Installing rolify (3.2.0) 
Installing rspec-core (2.12.0) 
Installing rspec-expectations (2.12.0) 
Installing rspec-mocks (2.12.0) 
Installing rspec-rails (2.12.0) 
Installing sexp_processor (4.1.2) 
Installing ruby_parser (3.0.1) 
Installing sass-rails (3.2.5) 
Installing simple_form (2.0.4) 
Installing sqlite3 (1.3.6) with native extensions 
Installing thin (1.5.0) with native extensions 
Installing uglifier (1.3.0) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install

> = 1.9.2 : nothing to do! Yay!

Post-install message from hub:

---

```
              You there! Wait, I say!
              =======================

   If you are a heavy user of `git` on the command
   line  you  may  want  to  install `hub` the old
   fashioned way.  Faster  startup  time,  you see.

   Check  out  the  installation  instructions  at
   https://github.com/defunkt/hub#readme  under the
   "Standalone" section.

   Cheers,
   defunkt
```

---

```
composer  Running 'after bundler' callbacks.
```

The template [https://raw.github.com/RailsApps/rails-composer/master/composer.rb] could not be loaded. Error: You have already activated rake 0.9.2.2, but your Gemfile requires rake 10.0.2. Using bundle exec may solve this.

**Comment by DanielKehoe** [comment]
See the Rails Composer README Troubleshooting section. It points to the article:
http://railsapps.github.com/rails-error-you-have-already-activated.html

Basically, try uninstalling rake and installing it again.
