### ISSUE TITLE
database.yml missing from repo

### ISSUE THREAD

**Issue by mattslay** [RailsApps/rails3-bootstrap-devise-cancan#2]
After I cloned this from GitHub, I found that it is missing the database.yml file form the Config folder.

Here is the error message I got when running the app for the first time:

   "No such file or directory - /Users/matt/Repos/rails3-bootstrap-devise-cancan/config/database.yml"

So, I just copied a version of that file from a regular default Rails app, and then it worked fine.

**Comment by DanielKehoe** [comment]
Thanks! Good catch. I'd blocked it from a commit using .gitignore. Pushed a copy to the repo and should be all good now.
