### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rutte** [RailsApps/rails3-bootstrap-devise-cancan#20]
The projects would be 100% if during the setup one could select items to create different combos. For instance:
Select database
1-Sqlite3
2-MySql
3-Postgresql
4-Mongoid
5-Mongodb
...

Select auth
1-none
2-Devise
3-OmniAuth
...

Select templates
1-none
2-Twitter bootstrap
3-Boilerplate
...

**Comment by DanielKehoe** [comment]
Take a look at Rails Composer:
http://railsapps.github.com/rails-composer

Select "Build my own application."
