### ISSUE TITLE
certificate verify failed (again, sorry)

### ISSUE THREAD

**Issue by kiote** [RailsApps/rails3-bootstrap-devise-cancan#3]
Sorry, but

```
cd /opt/local/etc/openssl 
```

says "no such file", even more, I don't have /opt directory on my MacOS 10.7.3 system. Maybe this (http://railsapps.github.com/openssl-certificate-verify-failed.html) solution works only for 10.6.8? Or, as far as I understood /opt exisit only if I use macports, so I don't (ant think some of Mac users, too).

**Comment by DanielKehoe** [comment]
The article http://railsapps.github.com/openssl-certificate-verify-failed.html has been recently updated and may provide a solution.
