### ISSUE TITLE
Dead links in Readme starting with `http://railsapps.github.com/`

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-bootstrap-devise-cancan#35]
In README.textile, there are many dead links which start with `http://railsapps.github.com/`.

**Comment by DanielKehoe** [comment]
GitHub recently transitioned `http://railsapps.github.com/` addresses to `http://railsapps.github.io/`.

But all the addresses should be automatically redirected. Which ones are dead?

**Comment by MarkDBlackwell** [comment]
For me in SeaMonkey, http://railsapps.github.io works.

http://railsapps.github.com redirects to https://railsapps.github.com which fails, giving connection refused.

In Firefox, http://railsapps.github.com redirects and fails in the same way.

All the links starting with http://railsapps.github.com/ are failing for me.

**Comment by MarkDBlackwell** [comment]
The problem was caused by the following:

I had assumed everything under github.com was using [Transport Layer Security[(http://en.wikipedia.org/wiki/Transport_Layer_Security) (which means it uses the https:// protocol).

I had assumed this ultimately because of all the [news](https://github.com/blog/search?q=SSL) in their blog regarding the use of TLS (and seemingly its site-wide adoption) by GitHub.

So therefore in my NoScript settings, under NoScript-Advanced-HTTPS-'Force the following sites to use secure (HTTPS) connections', I had included:

`*.github.com`.

The world is moving toward universal use of TLS it seems. I understand this is being encouraged by Google, possibly for good reason.

After I changed this line to just `github.com`, then your site (http://railsapps.github.com) now redirects and works okay. I guess it's a small-volume issue.

However, if you additionally were to ask GitHub to redirect https://railsapps.github.com/ (to http://railsapps.github.io/) as well, then that also I think would take care of any other people who (like me) assume all subdomains under github.com use TLS.

**Comment by MarkDBlackwell** [comment]
I am aware that https://railsapps.github.com/ doesn't redirect anywhere, currently.

I read this GitHub [article](https://github.com/blog/1452-new-github-pages-domain-github-io) on the current changeover as saying they will help: 'Please contact support if you experience any issues due to these changes.'

Here's NoScript's [discussion](http://noscript.net/faq#qa6_1) of https:// which of course is important to use if possible.

It would seem good for users of RailsApps to be able to include the protection NoScript affords, of enforcing that their access to github.com is always by means of https://.

**Comment by DanielKehoe** [comment]
@MarkDBlackwell check the links, please.

**Comment by MarkDBlackwell** [comment]
Sure; a source view (of the [repository](https://github.com/RailsApps/rails3-bootstrap-devise-cancan) page) confirms you now improved almost all those links (in this repository page) to your RailsApps subdomain (formerly of github.com, now of github.io) that didn't work (in this https:// sense).

Only one such link (to http://railsapps.github.com/ ) remaining in the repository description (not the readme) still fails.

It's too bad GitHub didn't solve this little problem in one place by redirecting https://railsapps.github.com/ for all your repositories, though!

**Comment by DanielKehoe** [comment]
Thanks for pointing out the link in the repo description. I've made the update.
