### ISSUE TITLE
What is the correct way to update to Bootstrap version 2.0.3?

### ISSUE THREAD

**Issue by mattslay** [RailsApps/rails3-bootstrap-devise-cancan#4]
Twitter Bootstrap 2.0.3 was release today... So, what is the correct way to update the code that I cloned from here to this new version of Twitter Bootstrap?

**Comment by DanielKehoe** [comment]
Keep an eye on https://github.com/thomas-mcdonald/bootstrap-sass. Thomas McDonald has promised to keep the bootstrap_sass gem current with newest Twitter Bootstrap releases. When he releases an updated gem, "bundle update" should be enough to pull in the updated gem.

**Comment by mattslay** [comment]
The LESS "twitter-bootstrap-rails" released their update on the same day. Overall, the LESS one seems to be more active. I think I'm going to switch over.

https://github.com/seyhunak/twitter-bootstrap-rails
