### ISSUE TITLE
Is config/application.yml hidden via .gitignore?

### ISSUE THREAD

**Issue by dklounge** [RailsApps/rails3-bootstrap-devise-cancan#45]
Is config/application.yml hidden via .gitignore? That doesn't seem to be default case.

**Comment by DanielKehoe** [comment]
I guess you mean _config/application.yml_. It is in the Git repo (so you'll have the file when you clone the repo). But you won't be able to check it in to a repo because it is listed in _.gitignore_.

If you mean _config/application.rb_, that should not be hidden.

**Comment by dklounge** [comment]
Thanks for clarifying.
