### ISSUE TITLE
Small issue with cucumber-rails in Gemfile

### ISSUE THREAD

**Issue by mattslay** [RailsApps/rails3-bootstrap-devise-cancan#6]
When running a test, I get this message:

```
WARNING: Cucumber-rails required outside of env.rb.  The rest of loading is being defered until env.rb is called.
To avoid this warning, move 'gem cucumber-rails' under only group :test in your Gemfile
```

Your template has the gem in the correct place, yet it still gives this error.

I found the fix here in this cucumber-rails pull request, which was accepted:
    https://github.com/cucumber/cucumber-rails/pull/209

You can see from the main gem page, that you must include ":require => false" to make the error go away.
    https://github.com/cucumber/cucumber-rails/blob/master/README.md

So, the line in the Gemfile should read:

```
gem "cucumber-rails", ">= 1.3.0", :group => :test, :require => false
```

**Comment by DanielKehoe** [comment]
Thank you for bringing this to my attention. I'll be updating the example Gemfile.
