### ISSUE TITLE
Twitter Bootstrap icons do not show up...

### ISSUE THREAD

**Issue by mattslay** [RailsApps/rails3-bootstrap-devise-cancan#7]
If you try to use a Twitter Bootstrap icon, it will not show up. This is an issue with the code used in the bootstrap_and_overrides.css.scss file.

These are the correct lines that need to be used in that file:

```
$iconSpritePath: asset-url('glyphicons-halflings.png', image);
$iconWhiteSpritePath: asset-url('glyphicons-halflings-white.png', image);
```

I found the fix for this issue here: https://github.com/thomas-mcdonald/bootstrap-sass/issues/105

**Comment by DanielKehoe** [comment]
Thanks for researching the issue and proposing a fix. I'll be updating the example.
