### ISSUE TITLE
Conditional in Gemfile causes problems with Heroku deployment

### ISSUE THREAD

**Issue by averydev** [RailsApps/rails3-bootstrap-devise-cancan#8]
I believe this is because my dev environment is a Mac, and EC2 isn't. This creates a mismatch between the Gemfile.lock and the Gemfile

**Comment by DanielKehoe** [comment]
I don't understand. There is no conditional in the Gemfile. Could you explain?

**Comment by DanielKehoe** [comment]
I believe this was an issue with an earlier version that set a conditional test for the OS in the Gemfile to determine if therubyracer gem should be included. I removed the conditional test for the OS in the Gemfile so I'm closing this issue.
